### ISSUE TITLE
Rename IAaSwSIFT to IAaSwSIFT.py for syntax highlighting

### ISSUE THREAD

**Issue by pmh-only** [apwlq/learn_opencv#1]
Hell nah... why r u uploaded python script without extension?

That's UNACCEPTABLE

cc: @apwlq

**Comment by apwlq** [comment]
umm.. sorry..

**Comment by pmh-only** [comment]
jk that's oka when you just dumping some codes

**Comment by apwlq** [comment]
dONE!
